# Numpy

In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
myMat = [[1,2,3], [4,5,6],[7,8,9]]

In [6]:
np.array(myMat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.random.randint(1,100,30)

array([ 8, 73, 63, 68, 25, 42, 42, 19, 12, 80, 89, 82, 36, 37, 38, 33, 27,
        9, 68, 48, 53, 95,  3, 10, 29, 16, 66, 52, 55, 12])

In [9]:
arr = np.arange(25)

In [10]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [11]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [12]:
arr.max()

24

In [13]:
arr.min()

0

In [14]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

# # Pandas

In [15]:
import numpy as np
import pandas as pd

In [16]:
labels = ['a', 'b', 'c']
my_data = [10,20,30]
arr = np.array(my_data)
d = {'a':10, 'b':20, 'c':30}

In [17]:
pd.Series(data = my_data)

0    10
1    20
2    30
dtype: int64

In [18]:
pd.Series(data=my_data,index=labels)

a    10
b    20
c    30
dtype: int64

In [19]:
pd.Series(my_data,labels)

a    10
b    20
c    30
dtype: int64

In [20]:
a = pd.Series(labels)
print(a)

0    a
1    b
2    c
dtype: object


In [21]:
pd.Series(arr,labels)

a    10
b    20
c    30
dtype: int32

In [22]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [23]:
 ser1 = pd.Series([1,2,3,4],['USA','GERMANY','USSR','JAPAN'])

In [24]:
ser1


USA        1
GERMANY    2
USSR       3
JAPAN      4
dtype: int64

In [25]:
ser2 = pd.Series([1,2,5,4],['USA','GERMANY','ITALY','JAPAN'])

In [26]:
ser2

USA        1
GERMANY    2
ITALY      5
JAPAN      4
dtype: int64

In [27]:
ser1['GERMANY']

2

In [28]:
ser3 = pd.Series(data=labels)

In [29]:
ser3

0    a
1    b
2    c
dtype: object

In [30]:
ser1

USA        1
GERMANY    2
USSR       3
JAPAN      4
dtype: int64

In [31]:
ser2

USA        1
GERMANY    2
ITALY      5
JAPAN      4
dtype: int64

In [32]:
ser1 + ser2

GERMANY    4.0
ITALY      NaN
JAPAN      8.0
USA        2.0
USSR       NaN
dtype: float64

# Pandas - Data Frames

In [33]:
from numpy.random import randn

In [34]:
np.random.seed(101)

In [35]:
df = pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])

In [36]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [37]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [38]:
df[['W','X']]

W         X
A  2.706850  0.628133
B  0.651118 -0.319318
C -2.018168  0.740122
D  0.188695 -0.758872
E  0.190794  1.978757

In [39]:
df['new'] = df['W'] + df['X']
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.334983
B  0.651118 -0.319318 -0.848077  0.605965  0.331800
C -2.018168  0.740122  0.528813 -0.589001 -1.278046
D  0.188695 -0.758872 -0.933237  0.955057 -0.570177
E  0.190794  1.978757  2.605967  0.683509  2.169552

In [40]:
df.drop('new',axis=1,inplace=True)
#INPLACE MUST BE EQUALS TO TRUE IF YOU WANT EFFECT TO BE PERMANENT 

In [41]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [42]:
df.drop('E', axis=0)

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

In [43]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [44]:
# the number 5(row) is axis 0, and the number 4(columns) is axis 1
df.shape

(5, 4)

In [45]:
df[['W','Z']]

W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [46]:
#selecting rows

In [47]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [48]:
#there are two ways
df.loc['A']

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [49]:
#second method
df.iloc[2]

W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64

In [50]:
df.loc['B', 'Y']

-0.8480769834036315

In [51]:
df.loc[['A','B'],['W','Y']]

W         Y
A  2.706850  0.907969
B  0.651118 -0.848077

In [52]:
df.describe()

W         X         Y         Z
count  5.000000  5.000000  5.000000  5.000000
mean   0.343858  0.453764  0.452287  0.431871
std    1.681131  1.061385  1.454516  0.594708
min   -2.018168 -0.758872 -0.933237 -0.589001
25%    0.188695 -0.319318 -0.848077  0.503826
50%    0.190794  0.628133  0.528813  0.605965
75%    0.651118  0.740122  0.907969  0.683509
max    2.706850  1.978757  2.605967  0.955057

In [53]:
#Conditional Selector
booldf = df >0
booldf

W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [54]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [55]:
df['W']>0

A     True
B     True
C    False
D     True
E     True
Name: W, dtype: bool

In [56]:
df['W'] + df['X'] <2

A    False
B     True
C     True
D     True
E    False
dtype: bool

In [57]:
df[df['W'] + df['X'] <2]

W         X         Y         Z
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

In [58]:
df[df['Z']<0]

W         X         Y         Z
C -2.018168  0.740122  0.528813 -0.589001

In [59]:
resultdf = df[df['W']>0]
resultdf

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [60]:
resultdf['X']

A    0.628133
B   -0.319318
D   -0.758872
E    1.978757
Name: X, dtype: float64

In [61]:
df[df['W']>0]['X']

A    0.628133
B   -0.319318
D   -0.758872
E    1.978757
Name: X, dtype: float64

In [62]:
df[df['W']>0][['Y','Z']]

Y         Z
A  0.907969  0.503826
B -0.848077  0.605965
D -0.933237  0.955057
E  2.605967  0.683509

In [63]:
#handling multiple conditions
df[(df['W']>0) & (df['Y']>1)] #and operation

W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509

In [64]:
#handling multiple conditions
df[(df['W']>0) | (df['Y']>1)] #or operation

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [65]:
#Reseting the index
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [66]:
df.reset_index()

index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [67]:
#Method two
newindex = 'CA NY WY OR CO'.split()
newindex

['CA', 'NY', 'WY', 'OR', 'CO']

In [68]:
df['States'] = newindex
df

W         X         Y         Z States
A  2.706850  0.628133  0.907969  0.503826     CA
B  0.651118 -0.319318 -0.848077  0.605965     NY
C -2.018168  0.740122  0.528813 -0.589001     WY
D  0.188695 -0.758872 -0.933237  0.955057     OR
E  0.190794  1.978757  2.605967  0.683509     CO

In [69]:
df.set_index('States')

W         X         Y         Z
States                                        
CA      2.706850  0.628133  0.907969  0.503826
NY      0.651118 -0.319318 -0.848077  0.605965
WY     -2.018168  0.740122  0.528813 -0.589001
OR      0.188695 -0.758872 -0.933237  0.955057
CO      0.190794  1.978757  2.605967  0.683509

In [70]:
# Index Levels
outside = ['G1','G1','G1','G2','G2','G2','G2',]
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_ideex = pd.MultiIndex.from_tuples(hier_index)

# Pandas Missing Values

In [74]:
e = {'A':[1,2,np.nan],'B':[5,np.nan,np.nan],'C':[1,2,3]}
e

{'A': [1, 2, nan], 'B': [5, nan, nan], 'C': [1, 2, 3]}

In [76]:
df = pd.DataFrame(e)
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [77]:
df.dropna() #it drops any row with one or more null values

A    B  C
0  1.0  5.0  1

In [78]:
df.dropna(axis=1) #it drops any column with one or more null values

C
0  1
1  2
2  3

In [83]:
df.dropna(thresh= 2)

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [84]:
df.fillna(value='fill value')

A           B  C
0           1           5  1
1           2  fill value  2
2  fill value  fill value  3

In [86]:
df.iloc[1].fillna(value=df.iloc[1].mean())

A    2.0
B    2.0
C    2.0
Name: 1, dtype: float64

In [87]:
df['A'].fillna(value=df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [91]:
df.isnull()

A      B      C
0  False  False  False
1  False   True  False
2   True   True  False

In [92]:
df.isnull().sum()

A    1
B    2
C    0
dtype: int64

# Group By

In [93]:
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person': ['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales': [200,120,340,124,243,350]}

In [95]:
df = pd.DataFrame(data)
df

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [96]:
byComp = df.groupby('Company')

In [97]:
byComp.mean()

Sales
Company       
FB       296.5
GOOG     160.0
MSFT     232.0

In [98]:
byComp.sum()

Sales
Company       
FB         593
GOOG       320
MSFT       464

In [99]:
byComp.max()

Person  Sales
Company                
FB         Sarah    350
GOOG         Sam    200
MSFT     Vanessa    340

In [100]:
byComp.min()

Person  Sales
Company                
FB          Carl    243
GOOG     Charlie    120
MSFT         Amy    124

In [101]:
df.groupby('Company').sum().loc['FB']

Sales    593
Name: FB, dtype: int64

In [102]:
df.describe()

Sales
count    6.000000
mean   229.500000
std    100.899455
min    120.000000
25%    143.000000
50%    221.500000
75%    315.750000
max    350.000000

In [103]:
df.groupby('Company').describe()

Sales                                                        
        count   mean         std    min     25%    50%     75%    max
Company                                                              
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

NameError: name 'numpy' is not defined